SimulacionFrijol/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.login_registrar.views import handler404,handler500
from django.conf.urls import handler404,handler500
 

handler404=handler404 
handler500=handler500
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^simula/', include('apps.configurarSimulacion.urls',namespace="configurar")),
    
    url(r'^',include('apps.login_registrar.urls',namespace="login")),
    url(r'^nuevo/',include('apps.nuevo_editar.urls',namespace="nuevo")),
    url(r'^consultar/',include('apps.consultar.urls',namespace="consulta")),

    #AQUI VAN A AGREGAR CADA UNO SUS URL GLOBLAES, Y CADA QUIEN TRABAJARA EN SU APPS ASIGNADA,
    # NO TOQUEN LAS URLS YA DEFINIDAS SIN PREVIO AVISO EN EL GRUPO
]

apps/consultar/urls.py
from django.conf.urls import url,include
from apps.consultar.views import *


 
urlpatterns=[
 url(r'^simulaciones$',simulacionlist,name='consultar'),
 url(r'^editar/(?P<idSimulacion>\d+)/$',simulacionEditar,name='editar'),
  url(r'^eliminarSimulacion/(?P<idSimulacion>\d+)$',simulacionEliminar,name='eliminar'),
  url(r'^buscar$',buscar,name='buscar'),

]

apps/login_registrar/urls.py
from django.conf.urls import url,include
from apps.login_registrar.views import *
app_name='login_registrar'
urlpatterns=[
 url(r'^$',login, name='log'), 
 url(r'^registrar/$',registrar,name='registrar'), 
 url(r'^logout/$',logout,name='lo'),
 url(r'^404/$',handler404,name='404'),
 url(r'^500/$',handler500,name='500'),





]

apps/nuevo_editar/urls.py
from django.conf.urls import url,include
from apps.nuevo_editar.views import simulacionCrear,index,simular,somos,jsonParametros,simularVer
#,grafico

urlpatterns=[
url(r'^inicio$',index,name='inicio'),
url(r'^simulacion$',simulacionCrear,name='nuevaSimulacion'),
#url(r'^grafico/(?P<idSimulacion>\d+)/$',grafico,name='graficos'),
url(r'^simular$',simular,name='simula'),
url(r'^simularVer/(?P<idSimulacion>\d+)/$',simularVer,name='simularVer'),
#url(r'^editarSimulacion/(?P<idSimulacion>\d+)/$',simulacionEditar,name='editar'),
url(r'^somos$',somos,name='somos'),
url(r'^consultaGrafico$',jsonParametros,name='ajaxConsulta'),


]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}Document{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/estilo.css" %}">

	
	<script src="{% static "bootstrap/js/jquery.min.js" %}"></script>
	<script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>	
  	<link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
  	
  	
  	

</head>
<body>
	<div class="container">
		
	{% block navbar%}
      	<header>
      		<nav class="navegacion">
      			<ul class="menu">
      				<li><a href="{% url 'nuevo:inicio'%}">Inicio</a></li>
      				<li><a href="{% url 'nuevo:somos' %}">SimulaFri</a></li>
      				<li><a href="{% url 'nuevo:nuevaSimulacion' %}">Nueva Simulacion</a></li>
      				<li><a href="{% url 'consulta:consultar'%}">Mis simulaciones</a></li>
      				<li><a href="">Opciones</a>
						<ul class="submenu">
							<li><a href="{% url 'login_registrar:lo' %}">Salir</a></li>
						</ul>
      				</li>
      				<li id="usro">
      				<strong>{{user.username}}</strong>
      			</li>

      			</ul>
      		</nav>
      	</header>
	
	{% endblock %}

	{%  block jquery %}

	{% endblock %}

	{% block content%}
	<h1>Contenido del formulario</h1>
	{% endblock %}
  
	
</div>
 
</body>
<footer>
	{% block footer %}
	
	{% endblock %}
</footer>
</html>

templates/base/menu.html
<div class="container">
		<header>
			<nav class="navegacion">
      			<ul class="menu">
      				<li><a href="{% url 'nuevo:inicio'%}">Inicio</a></li>
                              <li><a href="{% url 'nuevo:somos' %}">SimulaFri</a></li>
                              <li><a href="{% url 'nuevo:nuevaSimulacion' %}">Nueva Simulacion</a></li>
                              <li><a href="{% url 'consulta:consultar'%}">Mis simulaciones</a></li>
                              <li><a href="">Opciones</a>
                                    <ul class="submenu">
                                          <li><a href="{% url 'login_registrar:lo' %}">Salir</a></li>
                                    </ul>
                              </li>
      				<li>
      			</li>

      			</ul>
      		</nav>
		</header>
		
	</div>