SimulacionFrijol/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.login_registrar.views import handler404,handler500
from django.conf.urls import handler404,handler500
 

handler404=handler404 
handler500=handler500
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^simula/', include('apps.configurarSimulacion.urls',namespace="configurar")),
    
    url(r'^',include('apps.login_registrar.urls',namespace="login")),
    url(r'^nuevo/',include('apps.nuevo_editar.urls',namespace="nuevo")),
    url(r'^consultar/',include('apps.consultar.urls',namespace="consulta")),

    #AQUI VAN A AGREGAR CADA UNO SUS URL GLOBLAES, Y CADA QUIEN TRABAJARA EN SU APPS ASIGNADA,
    # NO TOQUEN LAS URLS YA DEFINIDAS SIN PREVIO AVISO EN EL GRUPO
]

apps/consultar/urls.py
from django.conf.urls import url,include
from apps.consultar.views import *


 
urlpatterns=[
 url(r'^simulaciones$',simulacionlist,name='consultar'),
 url(r'^editar/(?P<idSimulacion>\d+)/$',simulacionEditar,name='editar'),
  url(r'^eliminarSimulacion/(?P<idSimulacion>\d+)$',simulacionEliminar,name='eliminar'),
  url(r'^buscar$',buscar,name='buscar'),

]

apps/nuevo_editar/urls.py
from django.conf.urls import url,include
from apps.nuevo_editar.views import simulacionCrear,index,simular,somos,jsonParametros,simularVer
#,grafico

urlpatterns=[
url(r'^inicio$',index,name='inicio'),
url(r'^simulacion$',simulacionCrear,name='nuevaSimulacion'),
#url(r'^grafico/(?P<idSimulacion>\d+)/$',grafico,name='graficos'),
url(r'^simular$',simular,name='simula'),
url(r'^simularVer/(?P<idSimulacion>\d+)/$',simularVer,name='simularVer'),
#url(r'^editarSimulacion/(?P<idSimulacion>\d+)/$',simulacionEditar,name='editar'),
url(r'^somos$',somos,name='somos'),
url(r'^consultaGrafico$',jsonParametros,name='ajaxConsulta'),


]

apps/consultar/models.py
from django.db import models

# Create your models here.

apps/grafico/models.py
from django.db import models

# Create your models here.

apps/consultar/views.py
from django.shortcuts import render,redirect,get_object_or_404,render_to_response
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.core.paginator import Paginator,PageNotAnInteger, EmptyPage
from django.http import HttpResponse
import json
from django.core import serializers

from apps.configurarSimulacion.models import Simulacion,Configuracion,Siembra,FaseCultivo,Usuario
#from apps.configurarSimulacion.forms import ConfigurarForm
 
# Create your views here.
#LISTAMOS LOS DATOS DE LA BASE DE DATOS, FILTRANDO POR USUARIO LOGUEADO
def simulacionlist(request):
	if not request.user.is_active:
			return redirect('/')
	us=request.user
	usua=Usuario.objects.get(nombre_usuario=us)
	simulacion = Simulacion.objects.filter(estado=1).filter(usuario=usua).order_by('-id')
	#PAGINADOR 
	paginador = Paginator(simulacion,5)
	page = request.GET.get('page')
	try:
		simulacion = paginador.page(page)
	except PageNotAnInteger:
		simulacion = paginador.page(1)
	except EmptyPage:
		simulacion = paginador.page(paginador.num_pages)
	contexto = {'simulaciones':simulacion }
	return render(request, 'Simulacion/consultar.html', contexto)

#FUNCION QUE NOS PERMITE EDITAR
@csrf_protect
def simulacionEditar(request,idSimulacion):
	if not request.user.is_active:
			return redirect('/')

	us=request.user
	usuario_id=Usuario.objects.get(nombre_usuario=us)
	simulacion = get_object_or_404(Simulacion,pk=idSimulacion)
	configura = get_object_or_404(Configuracion,pk=idSimulacion)
	
	siembras = Siembra.objects.get(id=1)
	#usuario_id =usua.id
	if request.method == 'POST':
		simulaElimina = Simulacion.objects.get(id=idSimulacion)
		simulaElimina.delete()
		simula = Simulacion()
		confi = Configuracion()
		fase = FaseCultivo()
		fase.germinacion=True if request.POST.get('germinacion') else False
		fase.mergencia=True if request.POST.get('emergencia') else False
		fase.hojaPrimaria=True if request.POST.get('hojaPrimaria') else False
		fase.primeraHoja=True if request.POST.get('primeraHoja') else False
		fase.terceraHoja=True if request.POST.get('terceraHoja') else False
		fase.prefloracion=True if request.POST.get('prefloracion') else False
		fase.floracion=True if request.POST.get('floracion') else False
		fase.save()
		fase_id = FaseCultivo.objects.latest('id')
		
		confi.temperaturaMax = request.POST['temperaturaMax']
		confi.temperaturaMin = request.POST['temperaturaMin']
		confi.humedad = request.POST['humedad']
		confi.altitud = request.POST['altitud']
		confi.luminosidad = request.POST['luminosidad']
		confi.distanciaLinea = request.POST['distanciaL']
		confi.save()
		confi_id = Configuracion.objects.latest('id')
		simula.nombre = request.POST['simulacion']
		simula.lineaSiembra = request.POST['linea']
		simula.estado = 1
		simula.siembra = siembras
		simula.usuario = usuario_id
		simula.configuracion=confi_id
		simula.faseCultivo = fase_id
		simula.save()

		

		return redirect('consulta:consultar')
	else:
		contexto = {'simula':simulacion,'confi':configura,'siembras':siembras}
		#contexto.update(csrf(request))
		return render(request,'Simulacion/editarSimulacion.html',contexto)
#FUNCION QUE NOS PERMITE ELIMINAR UN REGISTRO
def simulacionEliminar(request,idSimulacion):
	if not request.user.is_active:
			return redirect('/')

	simulacion = get_object_or_404(Simulacion,pk=idSimulacion)
	configura = get_object_or_404(Configuracion,pk=idSimulacion)
	simula2 = Simulacion.objects.get(id=idSimulacion)
	simula2 = Simulacion.objects.get(id=idSimulacion)
	nombre=simulacion.nombre
	if request.method == 'POST':
		simula2.delete()
		return redirect('consulta:consultar')
	else:
		return render(request,'Simulacion/simulaciondelete.html',context={'nombre':nombre})


#FUNCION QUE NOS PERMITE HACER BUSQUEDA DE UNA SIMULAACION
def buscar(request):
	if not request.user.is_active:
			return redirect('/')

	nombre = request.GET.get('title') #DICCIONARIO
	simulas = Simulacion.objects.filter(nombre__startswith=nombre)
	simulas = [simula_serializer(simula) for simula in simulas] #obteniendo lista de diccionarios
	return render(request,'Simulacion/consultar.html',{'buscaSimula':simulas})


#SERIALIZANDO
def simula_serializer(simula):
	return {'id':simula.id,'nombre':simula.nombre,'linea':simula.lineaSiembra,'siembra':simula.siembra.nombre}

apps/grafico/views.py
from django.shortcuts import render

# Create your views here.

templates/Simulacion/configuracion.html
{% extends 'base/base.html'%}
{% load staticfiles %}
{%block title%}Configuracion{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static "css/configuracion.css" %}"/>
<form method="POST">
	{% csrf_token %}
	<div class="form-group">
		<h2>Configuracion Base</h2>
		<div>
		<p>Temperatura Maxima</p>
		<input  class="form-control" type="number" name="temperaturaMax" id="temperaturaMax">
		</div>

		<div>
	    <p>Temperatura Minima</p>
		<input  class="form-control" type="number" name="temperaturaMin" id="temperaturaMin">
		</div>

		<div>
	    <p>Humedad</p>
		<input  class="form-control" type="number" name="humedad" id="humedad">
		</div>

		<div>
	    <p>Altitud</p>
		<input  class="form-control" type="number" name="altitud" id="altitud">
		</div>

		<div>
	    <p>Luminosidad</p>
		<input  class="form-control" type="number" name="luminosidad" id="luminosidad">
		</div>

		<div>
	    <p>Distancia Lineal</p>
		<input  class="form-control" type="number" name="distanciaL" id="distanciaL">
	    </div>

	</div>
</br>
	<div class="botones">
        <button type="submit" class="btn btn-primary btn-block">Guardar</button>
        <a class="btn btn-danger btn-block" href="">Cancelar</a>
    </div>
</form>
	
{% endblock %} 

templates/Simulacion/consultar.html
{% extends 'base/base.html' %}
{% block title%}Consultar{% endblock %}

{% block content %}

<form method="GET" action="{% url 'consulta:buscar' %}" id="buscarSimulacion">
	<div>
		<input type="text" name="title" >
		<input type="submit" name="" value="buscar" class="btn btn-primary">
	</div>
</form>
<table class="table table-bordered">
	<thead>
		<tr>
			<td>Nombre</td>
			<td>Linea de siembra</td>
			<td>Siembra</td>
			<td>Acciones</td>
		</tr>
	</thead>

	<tbody>
	{% if buscaSimula%}
		{% for busca in buscaSimula%}
		
		<tr>
				<td>{{ busca.nombre }}</td>
				<td>{{ busca.linea }}</td>
				<td>{{ busca.siembra }}</td>
				<td>
					<a class="btn btn-primary" href="{% url 'consulta:editar' busca.id %}">Editar</a>
					<a class="btn btn-danger" href="{%url 'consulta:eliminar' busca.id %}">Eliminar</a>
					<a  class="btn btn-info" href="{% url 'nuevo:simularVer' busca.id %}">Ver</a>
				</td>
		</tr>
		{% endfor %}

	{% else %}
		{% if simulaciones %}
			{% for simulacion  in simulaciones %}
			<tr>
				<td>{{ simulacion.nombre }}</td>
				<td>{{ simulacion.lineaSiembra }}</td>
				<td>{{ simulacion.siembra.nombre }}</td>
				<td>
					<a class="btn btn-primary" href="{% url 'consulta:editar' simulacion.id %}">Editar</a>
					<a class="btn btn-danger" href="{%url 'consulta:eliminar' simulacion.id %}">Eliminar</a>
					<a  class="btn btn-info" href="{% url 'nuevo:simularVer' simulacion.id %}">Ver</a>
				</td>
			</tr>

		{% endfor %} 

		{% else %}
		<h1>No hay registros de simulaciones</h1>

		{% endif %}
	{% endif %}
	</tbody>

{% endblock %}

{% block footer %}
<form>                
  <div class="pagination">
    <div class="section-inner clearfix">
        <p>
            {% if simulaciones.has_previous %}
                <a href="?page={{ simulaciones.previous_page_number }}">&lt; Prev</a> |
            {% endif %}

            {% if simulaciones.has_next %}
                <a href="?page={{ simulaciones.next_page_number }}">Next &gt;</a>
            {% endif %}

            <span>Page {{ simulaciones.number }} of {{ simulaciones.paginator.num_pages }}</span>
        </p>
    </div>
</div>
</form>

{% endblock %}

templates/Simulacion/grafico.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Grafico</title>
	<script type="application/javascript" src="/static/js/Chart.bundle.js"></script>
	<script type="application/javascript" src="/static/js/jquery-1.12.0.min.js" ></script>
	<script  type="application/javascript" src="/static/js/jquery2.min.js"  ></script>


	<link rel="stylesheet" type="text/css" href="{% static "css/estilo2.css" %}">

	<script type="text/javascript">

	var endpoint = '{% url 'nuevo:ajaxConsulta' %}';
	$.ajax({
		method:"GET",
		url:endpoint,
		success: function(data){
			console.log(data);

		},
	})
	var humedad = "{{humedad|safe}}"
	var nodos = "{{nodos|safe}}";
	//console.log(nodos);
	var validar = "{{validar|safe}}";
	var arrayColor = ['rgba(255, 99, 132, 0.5)','rgba(54, 162, 235, 0.5)','rgba(255, 206, 86, 0.5)','rgba(75, 192, 192, 0.5)','rgba(153, 102, 255, 0.5)','rgba(255, 159, 64, 0.5)',];
     var arrayBorderColor = ['rgba(255,99,132,1)','rgba(54, 162, 235, 1)','rgba(255, 206, 86, 1)','rgba(75, 192, 192, 1)','rgba(153, 102, 255, 1)','rgba(255, 159, 64, 1)',];

		$(document).ready(function(){
	var datos = {
			type:"bar",
			data:{
				datasets:[{
					label:'Germinacion',
					data:[1,2,3,4,5
					],
				backgroundColor: arrayColor,
             borderColor: arrayBorderColor,
            borderWidth: 1
		}],	

           labels:[
          		 "Dia 1","Dia 2","Dia 3","Dia 4","Dia 5",
           ]
		},
		options:{
			responsive:true,
		}
      };
     
     var datos2 = {
			type:"bar",
			data:{
				datasets:[{
					label:'Emergencia',
					data:[1,2,3,4,5],
				backgroundColor: arrayColor,
             borderColor: arrayBorderColor,
            borderWidth: 1
		}],	

           labels:[
          		 "Dia 1","Dia 2",,
           ]
		},
		options:{
			responsive:true,
		}
      };

      var datos3 = {
			type:"bar",
			data:{
				datasets:[{
					label:'Hoja Primaria',
					data:[1,2,3,4,5],
				backgroundColor: arrayColor,
             borderColor: arrayBorderColor,
            borderWidth: 1
		}],	

           labels:[
          		 "Dia 1","Dia 2","Dia 3","Dia 4",
           ]
		},
		options:{
			responsive:true,
		}
      };

      var datos4 = {
			type:"bar",
			data:{
				datasets:[{
					label:'Primera Hoja',
					data:[1,2,3,4,5],
				backgroundColor: arrayColor,
             borderColor: arrayBorderColor,
            borderWidth: 1
		}],	

           labels:[
          		 "Dia 1","Dia 2","Dia 3","Dia 4","Dia 5",
           ]
		},
		options:{
			responsive:true,
		}
      };

      var datos5 = {
			type:"bar",
			data:{
				datasets:[{
					label:'Tercera Hoja',
					data:[1,2,3,4,5],
				backgroundColor: arrayColor,
             borderColor: arrayBorderColor,
            borderWidth: 1
		}],	

           labels:[
          		 "Dia 1","Dia 2","Dia 3","Dia 4","Dia 5","Dia 6","Dia 7",
           ]
		},
		options:{
			responsive:true,
		}
      };

      var datos6 = {
			type:"bar",
			data:{
				datasets:[{
					label:'Prefloracion',
					data:[1,2,3,4,5],
				backgroundColor: arrayColor,
             borderColor: arrayBorderColor,
            borderWidth: 1
		}],	

           labels:[
          		 "Dia 1","Dia 2","Dia 3","Dia 4","Dia 5","Dia 6","Dia 7","Dia 8","Dia 9",
           ]
		},
		options:{
			responsive:true,
		}
      };

      var datos7 = {
			type:"bar",
			data:{
				datasets:[{
					label:'Floracion',
					data:[1,2,3,4,5],
				backgroundColor: arrayColor,
             borderColor: arrayBorderColor,
            borderWidth: 1
		}],	

           labels:[
          		 "Dia 1","Dia 2","Dia 3","Dia 4",
           ]
		},
		options:{
			responsive:true,
		}
      };
        
        if(validar[1]==1){
      	var canvas = document.getElementById("chart").getContext("2d");
        window.bar = new Chart(canvas,datos);
        }
        if(validar[4]==1){
        var canvas2 = document.getElementById("chart2").getContext("2d");
        window.bar2 = new Chart(canvas2,datos2);
        }
      	if(validar[7]==1){
        var canvas3 = document.getElementById("chart3").getContext("2d");
        window.bar3 = new Chart(canvas3,datos3);
		}
		if(validar[10]==1){
        var canvas4 = document.getElementById("chart4").getContext("2d");
        window.bar4 = new Chart(canvas4,datos4);
		}
		if(validar[13]==1){
        var canvas5 = document.getElementById("chart5").getContext("2d");
        window.bar5 = new Chart(canvas5,datos5);
        }
        if(validar[16]==1){
        var canvas6 = document.getElementById("chart6").getContext("2d");
        window.bar6 = new Chart(canvas6,datos6);
        }
        if(validar[19]==1){
        var canvas7 = document.getElementById("chart7").getContext("2d");
        window.bar7 = new Chart(canvas7,datos7);
        }
	});
 
</script>

</head>
<body>
	
	{% include 'base/menu.html' %}
	<h1 style="text-align: center"><strong>{{ simula.nombre }}</strong></h1>
<style type="text/css">
	#canvas-container{
		margin:30px auto;
	}
	#titulo{
	margin: 30px auto;
	}
</style>

 {% if simula.faseCultivo.germinacion  %}
   <h1 id="titulo" style="text-align: center"><strong> Germinacion</strong></h1>
  
 
   <div id="canvas-container"  style="width:50%;">
		<canvas id="chart" width="300" height="150"></canvas>
   </div>
   <h4 id="titulo" style="text-align: center"><strong> Dias</strong></h4>
 {% endif %}
 {% if simula.faseCultivo.mergencia %}
   <h1 id="titulo" style="text-align: center"><strong id="titulo">Emergencia</strong></h1>
   <div id="canvas-container"  style="width:50%;">
		<canvas id="chart2" width="300" height="150"></canvas>
   </div>
   <h4 id="titulo" style="text-align: center"><strong> Dias</strong></h4>
 {% endif %}
 {% if simula.faseCultivo.hojaPrimaria %}
  <h1 id="titulo" style="text-align: center"><strong id="titulo">Hoja Primaria</strong></h1>
   <div id="canvas-container"  style="width:50%;">
		<canvas id="chart3" width="300" height="150"></canvas>
   </div>
   <h4 id="titulo" style="text-align: center"><strong> Dias</strong></h4>
 {% endif %}
 {% if simula.faseCultivo.primeraHoja %}
  <h1 id="titulo" style="text-align: center"><strong id="titulo">Primera Hoja </strong></h1>
   <div id="canvas-container"  style="width:50%;">
		<canvas id="chart4" width="300" height="150"></canvas>
   </div>
   <h4 id="titulo" style="text-align: center"><strong> Dias</strong></h4>
 {% endif %}
 {% if simula.faseCultivo.terceraHoja %}
  <h1 id="titulo" style="text-align: center"><strong id="titulo">Tercera Hoja</strong></h1>
   <div id="canvas-container"  style="width:50%;">
		<canvas id="chart5" width="300" height="150"></canvas>
   </div>
   <h4 id="titulo" style="text-align: center"><strong> Dias</strong></h4>
 {% endif %}
 {% if simula.faseCultivo.prefloracion %}
  <h1 id="titulo" style="text-align: center"><strong id="titulo">Prefloracion</strong></h1>
   <div id="canvas-container"  style="width:50%;">
		<canvas id="chart6" width="300" height="150"></canvas>
   </div>
   <h4 id="titulo" style="text-align: center"><strong> Dias</strong></h4>
 {% endif %}
 {% if simula.faseCultivo.floracion %}
  <h1 id="titulo" style="text-align: center"><strong id="titulo">Floracion</strong></h1>
   <div id="canvas-container"  style="width:50%;">
		<canvas id="chart7" width="300" height="150"></canvas>
   </div>
   <h4 id="titulo" style="text-align: center"><strong> Dias</strong></h4>
 {% endif %}
</br>
{% for b in tiempo %}
  {% if b != 0 %}
  {{b}}
  {% endif %} 
{% endfor %}
</br>
{% for a in nodos %}
 {% if a != 0 %}
   {{a}}
 {% endif %}

{% endfor %}

</body>
</html>



	

templates/Simulacion/index.html
{% extends 'base/base.html'%}


{% block content %}
<h1> CONTENIDO SOBRE EL SOFTWARE DE SIMULACION</h1>
{% endblock %}

templates/Simulacion/nuevo.html
{% extends 'base/base.html'%}
{% load staticfiles %}
{% block title%}Nuevo {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static "css/nuevo.css" %}"/>
<script type="text/javascript" src="/static/js/validarFormNuevo.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
	
</script>
<form class="formulario" name="frmDatos" method="POST" onsubmit="return validaDatos()">
	 {% csrf_token %}

   
	<div class="form-group ">
		<div class="form-group">
			<p><strong>Nombre Simulacion:</strong></p>
			<input type="text" name="simulacion"  class="form-control" id="nombreSimulacion" required="required" />
		</div>
		<div class="form-group">
			<label for="ex1"><strong>Lineas de siembra:</strong></label>
			<input type="number" name="linea" id="ex1" class="form-control" id="lineaSiembra" placeholder="Maximo 99 lineas" required="required" min="1" max="99"/>
		</div>
		</br>
		<div class="form-group">
			<label><strong>Siembra:</strong></label>
			<h2>{{siembras.nombre}}</h2>
		</div>
		<div class="form-group">
			<strong>Fases de cultivo</strong>
		</br>
		
			<div>
			<input type="checkbox"  name="germinacion" id="germinacion"  />
			<strong>Germinacion</strong>
			</div>
			<div>
			<input type="checkbox"  name="emergencia" id="emergencia"  />
			<strong>Emergencia</strong>
			</div>
			<div>
			<input type="checkbox"  name="hojaPrimaria" id="hojaPrimaria"  />
			<strong>Hojas Primarias</strong>
			</div>
			<div>
			<input type="checkbox"  name="primeraHoja" id="primeraHoja"  />
			<strong>Primera Hoja Trifoliada</strong>
			</div>
			<div>
			<input type="checkbox"  name="terceraHoja" id="terceraHoja"  />
			<strong>Tercera Hoja Trifoliada</strong>
			</div>
			<div>
			<input type="checkbox"  name="prefloracion" id="prefloracion"  />
			<strong>Prefloracion</strong>
			</div>
			<div>
			<input type="checkbox"  name="floracion" id="floracion"  />
			<strong>Floracion</strong>
			</div>
			<a href="javascript:seleccionar_todo()"><strong>Marcar todos</strong></a> | 
			<a href="javascript:deseleccionar_todo()"><strong>Desmarcar</strong></a>
			
		    
		</div>
	</div>

    <div class="container">
    	<button type="button" class="btn btn-info " data-toggle="modal" data-target="#myModal">Configuracion</button>
		<button type="submit" class="btn btn-primary ">Guardar</button>
        <a class="btn btn-danger " href="{% url 'nuevo:inicio' %}">Cancelar</a>
    </div>
	<div class="container">
		
	  <div class="modal fade" id="myModal" role="dialog">
    	<div class="modal-dialog">
    	 <div class="modal-content">
           <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal">&times;</button>
               <h4 class="modal-title">Configuracion Base</h4>
           </div>
           <div class="modal-body">
           	{% csrf_token %}
         <!-- 	{{ form2.as_p}}-->
         	  <div class="form-group">	
              <label>Temperatura Maxima</label>
              <input type="range" step="0.01" name="temperaturaMax" id="temperaturaMax" value="34" placeholder=" Maximo 45 Centigrados" class="form-control" required="required" min="25" max="45" />
              <input type="text" name="valoredad" id="valoredad"  disabled="" value="34" />
              </div>
              <div class="form-group">
              <label>Temperatura Minima</label>
              <input type="range" step="0.01" name="temperaturaMin" id="temperaturaMin" value="10" placeholder="Minimo 5 Centigrados" class="form-control" required="required" min="5" max="20"/>
              <input type="text" name="valoredad2" id="valoredad2" disabled="" value="10">
              </div>
              <div class="form-group">
              <label>Humedad</label>
              <input type="range" step="0.01" name="humedad" id="humedad" value="500" placeholder="milimetros lluvia" class="form-control" required="required" min="150" max="1000"/>
              <input type="text" name="valoredad3" id="valoredad3" disabled="" value="500">
              </div>
              <div class="form-group">
              <label>Altitud</label>
              <input type="range" step="0.01" name="altitud" id="altitud" value="500" placeholder="msnm" class="form-control" required="required" min="500" max="4500"/>
              <input type="text" name="valoredad4" id="valoredad4" disabled="" value="500">
              </div>
              <div class="form-group">
              <label>Luminosidad</label>
              <input type="range" step="0.01" name="luminosidad" id="luminosidad" value="50" placeholder="" class="form-control" required="required" min="50" max="99"/>
              <input type="text" name="valoredad5" id="valoredad5" disabled="" value="50">
              </div>
              <div class="form-group">
              <label>Distancia entre Linea</label>
              <input type="range" step="0.01" name="distanciaL" id="distanciaL" value="10" placeholder="centimetros" class="form-control" required="required" min="10" max="99"/>
              <input type="text" name="valoredad6" id="valoredad6" disabled="" value="10">
              </div>
           </div>
           <div class="modal-footer">
              <button type="button" class="btn btn-info" data-dismiss="modal" onsubmit="return validaDatos()">OK</button>
              <input type="reset" class="btn btn-default">
           </div>

         </div>

    	</div>
      </div>
	</div>

<script type="text/javascript">
	function seleccionar_todo(){ 
   for (i=0;i<document.frmDatos.elements.length;i++) 
      if(document.frmDatos.elements[i].type == "checkbox")	
         document.frmDatos.elements[i].checked=1 
} 

function deseleccionar_todo(){ 
   for (i=0;i<document.frmDatos.elements.length;i++) 
      if(document.frmDatos.elements[i].type == "checkbox")	
         document.frmDatos.elements[i].checked=0 
}
$(document).ready(function()
		{
		$('#temperaturaMax').change(function() {
		$('#valoredad').val($(this).val());
		});
		$('#temperaturaMin').change(function() {
		$('#valoredad2').val($(this).val());
		});
		$('#humedad').change(function() {
		$('#valoredad3').val($(this).val());
		});
		$('#altitud').change(function() {
		$('#valoredad4').val($(this).val());
		});
		$('#luminosidad').change(function() {
		$('#valoredad5').val($(this).val());
		});
		$('#distanciaL').change(function() {
		$('#valoredad6').val($(this).val());
		});
	});


</script>


	
</form>

{% endblock %}

templates/Simulacion/quienSomos.html
{% extends 'base/base.html'%}
{% load staticfiles %}
{% block title%}Quienes somos? {% endblock %}


{% block content %}
<h1>SOMOS UN GRUPO DE TRABAJO DE HDP GT 02,EQUIPO NUMERO 2</h1>
{% endblock %}

templates/Simulacion/simulaciondelete.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title%}Eliminar{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de  {{nombre}} ?</h3>
	
	<button class="btn btn-danger" type="submit">Si,eliminar</button>
	<a class="btn btn-default" href="{% url 'consulta:consultar' %}">Cancelar</a>
</form>
{% endblock %}