SimulacionFrijol/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.login_registrar.views import handler404,handler500
from django.conf.urls import handler404,handler500
 

handler404=handler404 
handler500=handler500
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^simula/', include('apps.configurarSimulacion.urls',namespace="configurar")),
    
    url(r'^',include('apps.login_registrar.urls',namespace="login")),
    url(r'^nuevo/',include('apps.nuevo_editar.urls',namespace="nuevo")),
    url(r'^consultar/',include('apps.consultar.urls',namespace="consulta")),

    #AQUI VAN A AGREGAR CADA UNO SUS URL GLOBLAES, Y CADA QUIEN TRABAJARA EN SU APPS ASIGNADA,
    # NO TOQUEN LAS URLS YA DEFINIDAS SIN PREVIO AVISO EN EL GRUPO
]

apps/login_registrar/urls.py
from django.conf.urls import url,include
from apps.login_registrar.views import *
app_name='login_registrar'
urlpatterns=[
 url(r'^$',login, name='log'), 
 url(r'^registrar/$',registrar,name='registrar'), 
 url(r'^logout/$',logout,name='lo'),
 url(r'^404/$',handler404,name='404'),
 url(r'^500/$',handler500,name='500'),





]

templates/sesion/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login</title>
	<link rel="stylesheet" href="static/css/bootstrap.min.css">
<link rel="stylesheet" href="static/css/prueba.css">
</head>
<body>
	<div id="imagen">
		<img src="static/img/frijol.jpg" alt=" Quien sabe lo que siembra no le teme a lo que cosecha">
	 <h3> Quien sabe lo que siembra no le teme a lo que cosecha</h3>
</div>
	<div id="formulario2">
		<h1> Login</h1>
<div class="form-group" >
<form method="post">
{% csrf_token %}
 {{form.as_p}}
 
 <button type="submit" class="btn btn-primary">Login</button>
</form>
</div>
	{{error}}
	<br>
	<a href="{% url 'login_registrar:registrar' %}">¿ no tienes una cuenta? te invitamos a crear una</a>
	</div>
</body>
</html>

templates/sesion/registrar.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>signup</title>
<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
<link rel="stylesheet" href="{% static "css/prueba.css" %}">
<script type="application/javascript" src="/static/js/validarFecha.js"></script>
</head>

<body>
	<div id="formulario">

	<h1> signup</h1>
	
		<form method="post">
{% csrf_token %}
 {{form.as_p}}

 
 <button id="registrar" type="submit" class="btn btn-primary" onclick="myFunction()"> registrarse</button>
</form>
<div id="comprobando">
	{{error}}

	<a href="{% url 'login_registrar:log' %}">volver para iniciar sesion</a>
</div>
	

</div>
</body>
</html>